version: '3.9'
services:
  app:
    build:
      context: ./
      args:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
    env_file:
      - docker.env
    restart: on-failure
    ports:
      - "3000:3000"
